parameters:
#    happyr_birthday.example.class: Happyr\BirthdayBundle\Example

services:
  happyr.birthday.form.birthday:
    class: Happyr\BirthdayBundle\From\BirthdayType
    arguments: [@translator]
    tags:
      - { name: form.type, alias: happyr_birthday }